<?php
/**
 * Block Form in payment options
 *
 * @author KDS
 */
?>
<?php $_code = $this->getMethodCode(); ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none">
    <li>
        <?php if ($_code == 'onecheckout_bcaklikpay'): ?>
            You will be redirected to BCA KlikPay payment page when you place an order.
		    <?php elseif ($_code == 'onecheckout_installmentbni' || $_code == 'onecheckout_installmentmandiri'): ?>
            You will be redirected to <a onclick="window.open(this.href, 'http://www.doku.com')">DOKU</a> secure payment page when you place an order.
      <?php $installment_options = $this->getInstallmentOptions($_code); ?>
			<div>
				<label>Installment Options</label>
				<span>
					<select name="payment[installment_option]">
						<?php foreach ($installment_options as $key => $value): ?>
							<option value="<?php echo $value; ?>"><?php echo $key; ?> Months</option>
						<?php endforeach; ?>
					</select>
				</span>
			</div>
        <?php elseif ($_code == 'onecheckout_creditcard'): ?>
            You will be redirected to <a onclick="window.open(this.href, 'http://www.doku.com')">DOKU</a> secure payment page when you place an order. <br />Biaya Layanan 3% dari harga barang dan ongkos kirim + Rp2000.
        <?php elseif ($_code == 'onecheckout_permatava'): ?>
            You will be redirected to <a onclick="window.open(this.href, 'http://www.doku.com')">DOKU</a> secure payment page when you place an order. <br />Biaya Layanan Rp5000.
        <?php else: ?>
            You will be redirected to <a onclick="window.open(this.href, 'http://www.doku.com')">DOKU</a> secure payment page when you place an order.
        <?php endif; ?>
    </li>

    <?php if ($_img = $this->getPaymentImageSrc($_code)): ?>
        <li>
            <div style="padding:10px 15px 15px;">
                <img src="<?php echo $_img ?>" alt="" /><br />
            </div>
        </li>
    <?php endif; ?>

</ul>
